log_dir: "Checkpoint"
save_freq: 10
device: "cuda"
epochs: 100
batch_size: 64
pretrained_model: ""
train_data: "train_list.txt"
val_data: "val_list.txt"
num_workers: 0
base_dir: "StyleTTS2Omnidata"
rmvpe_path: "rmvpe.pt"
  
optimizer_params:
  lr: 0.0003
  
loss_params:
  lambda_f0: 0.1
  
